#!/usr/bin/env bash
#
# Flip the lab between github.com and the local Gitea instance.
#
#   ./compose/set-git-backend.sh gitea    # offline / conference mode
#   ./compose/set-git-backend.sh github   # back to normal
#
# The committed defaults are deliberately NOT all on the same side, so each
# direction overrides a different set:
#
#   cac_repo_url / ph_repo_url   default to github.com, because Octopus Cloud
#                                reads CaC from git and cannot reach
#                                host.docker.internal. `gitea` mode overrides.
#   gitops/** + gitops_repo_url  default to Gitea, because only the Argo CD in
#                                this local cluster ever reads them. `github`
#                                mode overrides.
#
# Consequence worth knowing: `gitea` mode rewrites ZERO files (it's the
# committed state), while `github` mode rewrites 12 gitops/ files and leaves
# them uncommitted. Gitea is the normal case; that asymmetry is the point.
#
# Why a generated tfvars file and not TF_VAR_* env vars: cac_repo_url and
# ph_repo_url are set in each stack's committed defaults.auto.tfvars, and
# *.auto.tfvars OUTRANK environment variables in OpenTofu's precedence order,
# so a TF_VAR_ export is silently ignored.
#
# !! The override filename must sort AFTER "defaults" !!
# *.auto.tfvars load lexicographically and later files win. "git-backend"
# beats "defaults" (g > d). An earlier attempt at "backend.auto.tfvars" was
# silently a no-op, because b < d meant defaults.auto.tfvars loaded last.
#
# Credentials are NOT touched here. The Makefile swaps them at apply time
# based on GITEA_ENABLED in .env, so no secret ends up in a tfvars file.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

BACKEND="${1:-}"
GITEA_USER="${GITEA_ADMIN_USER:-admin}"
GITEA_REPO="${GITEA_REPO:-octopus-iac-lab}"

# github.com forms
GH_WEB="https://github.com/creid-octopus/octopus-iac-lab"
GH_GIT="https://github.com/creid-octopus/octopus-iac-lab.git"
GH_CLONE="https://x-access-token:#{GitHub.Token}@github.com/creid-octopus/octopus-iac-lab.git"

# Gitea forms. host.docker.internal, NOT localhost or `gitea` — it's the only
# address that resolves from BOTH the Octopus container and Kubernetes pods.
# Verified: resolves to 192.168.65.254 in-cluster. See docs/local-gitea.md.
GT_WEB="http://host.docker.internal:3000/${GITEA_USER}/${GITEA_REPO}"
GT_GIT="http://host.docker.internal:3000/${GITEA_USER}/${GITEA_REPO}.git"
GT_CLONE="http://${GITEA_USER}:#{GitHub.Token}@host.docker.internal:3000/${GITEA_USER}/${GITEA_REPO}.git"

TFVARS_STACKS=(tofu/control-plane tofu/app-randomquotes tofu/platform-hub tofu/argocd)

# Generated per-stack override. Named for what it does rather than for one
# of the two backends, because BOTH directions need overrides — the
# committed defaults aren't all on the same side:
#
#   cac_repo_url / ph_repo_url  default to github.com, because Octopus Cloud
#                               reads CaC and cannot reach host.docker.internal
#   gitops_repo_url + gitops/   default to Gitea, because only the local
#                               cluster's Argo CD ever reads those
#
# So "gitea mode" overrides the first pair and "github mode" overrides the
# second. See docs/local-gitea.md.
OVERRIDE_FILE="git-backend.auto.tfvars"
LEGACY_OVERRIDE="gitea.auto.tfvars"   # pre-rename; removed on sight

clear_overrides() {
  local s
  for s in "${TFVARS_STACKS[@]}"; do
    [ -f "${s}/${OVERRIDE_FILE}" ] && rm -f "${s}/${OVERRIDE_FILE}" && info "cleared ${s}/${OVERRIDE_FILE}"
    [ -f "${s}/${LEGACY_OVERRIDE}" ] && rm -f "${s}/${LEGACY_OVERRIDE}" && info "removed legacy ${s}/${LEGACY_OVERRIDE}"
  done
  return 0
}

write_override() {
  local stack="$1" body="$2"
  cat > "${stack}/${OVERRIDE_FILE}" <<EOF
# Generated by compose/set-git-backend.sh — not committed, don't hand-edit.
# Overrides defaults.auto.tfvars (loads later alphabetically).
${body}
EOF
  info "wrote ${stack}/${OVERRIDE_FILE}"
}

step() { printf '\n=== %s\n' "$*"; }
info() { printf '    %s\n' "$*"; }

# In-place sed differs between BSD (macOS, needs an explicit empty suffix)
# and GNU (Linux, rejects it). Detect once rather than assuming macOS, so
# this is testable in a Linux container too.
if sed --version >/dev/null 2>&1; then
  sed_inplace() { sed -i "$@"; }
else
  sed_inplace() { sed -i '' "$@"; }
fi

# Rewrite one URL form to another across the files that hold it.
#
# Order within the sed matters: the credential-bearing clone URL and the
# `.git` form both CONTAIN the bare web form as a prefix, so they have to be
# replaced first or the bare-form rule would mangle them into a hybrid.
# `|` is the sed delimiter since every URL here contains `/` but none
# contain `|`. grep -F keeps the `.` in hostnames from acting as a wildcard.
flip_files() {
  local from_clone="$1" to_clone="$2" from_git="$3" to_git="$4" from_web="$5" to_web="$6"
  local changed=0 f

  while IFS= read -r f; do
    sed_inplace \
      -e "s|${from_clone}|${to_clone}|g" \
      -e "s|${from_git}|${to_git}|g" \
      -e "s|${from_web}|${to_web}|g" \
      "$f"
    info "  $f"
    changed=$((changed + 1))
  done < <(grep -rlF -e "${from_web}" -e "${from_clone}" \
             --include="*.yaml" --include="*.yml" --include="*.ocl" \
             gitops .octopus 2>/dev/null | sort -u)

  info "rewrote ${changed} file(s)"
}

# The Octopus feed resolves packages by id, and the two registries namespace
# differently: ghcr.io/creid-octopus/... vs the Gitea admin's own namespace.
# An earlier design created a Gitea org named creid-octopus so the ids would
# match exactly and this rewrite wouldn't be needed; dropped as unnecessary
# complexity (org creation needs a token scope we weren't requesting).
#
# So package_id becomes part of the switch. Must stay in step with
# REGISTRY_PATH in .gitea/workflows/build.yml.
GH_PKG="creid-octopus/octopus-iac-lab"
GT_PKG="${GITEA_USER}/${GITEA_REPO}"

flip_package_id() {
  local from="$1" to="$2" changed=0 f
  while IFS= read -r f; do
    sed_inplace "s|package_id = \"${from}\"|package_id = \"${to}\"|g" "$f"
    info "  $f"
    changed=$((changed + 1))
  done < <(grep -rlF "package_id = \"${from}\"" --include="*.ocl" .octopus 2>/dev/null | sort -u)
  info "rewrote package_id in ${changed} file(s)"
}

case "${BACKEND}" in
  gitea)
    step "Overriding the github-defaulted vars"
    clear_overrides
    # Only these two need overriding — gitops_repo_url already defaults to
    # Gitea, so no override for tofu/argocd.
    # control-plane carries the container registry too: same feed, different
    # URI, so the OCL's `feed = "ghcr"` and package_id keep working.
    write_override tofu/control-plane    "cac_repo_url          = \"${GT_GIT}\"
container_registry_url = \"http://host.docker.internal:3000\""
    write_override tofu/app-randomquotes "cac_repo_url = \"${GT_GIT}\""
    write_override tofu/platform-hub     "ph_repo_url  = \"${GT_WEB}\""

    step "Ensuring gitops/ URLs point at Gitea"
    # Normally a no-op: Gitea URLs are the committed default under gitops/.
    # Only does work if a previous `gitea-disable` left github URLs behind.
    flip_files "${GH_CLONE}" "${GT_CLONE}" "${GH_GIT}" "${GT_GIT}" "${GH_WEB}" "${GT_WEB}"

    step "Pointing OCL package_id at the Gitea registry namespace"
    flip_package_id "${GH_PKG}" "${GT_PKG}"

    step "Recording the switch in .env"
    if grep -q '^GITEA_ENABLED=' .env 2>/dev/null; then
      sed_inplace 's|^GITEA_ENABLED=.*|GITEA_ENABLED=true|' .env
    else
      echo "GITEA_ENABLED=true" >> .env
    fi
    info "GITEA_ENABLED=true — the Makefile now points Octopus's git credential at Gitea"

    cat <<EOF

=== Now on Gitea

  make cp-apply ph-apply app-apply   # Octopus CaC + Platform Hub → Gitea
  make argo-apply                    # bootstrap Application → Gitea

No gitea-push needed unless the rewrite above reported changed files —
gitops/ is committed as Gitea already, so this is normally a no-op.

Then verify per docs/local-gitea.md ("After switching backends").
EOF
    ;;

  github)
    step "Overriding the gitea-defaulted vars"
    clear_overrides
    # cac_repo_url / ph_repo_url already default to github, so only the
    # gitops source needs pushing back.
    write_override tofu/argocd "gitops_repo_url = \"${GH_WEB}\""

    step "Rewriting gitops/ URLs back to github.com"
    # This one DOES churn the working tree — gitops/ is committed as Gitea,
    # so running the lab without Gitea means uncommitted github URLs. That
    # asymmetry is intentional: Gitea is the normal case.
    flip_files "${GT_CLONE}" "${GH_CLONE}" "${GT_GIT}" "${GH_GIT}" "${GT_WEB}" "${GH_WEB}"

    step "Pointing OCL package_id back at GHCR"
    flip_package_id "${GT_PKG}" "${GH_PKG}"

    step "Recording the switch in .env"
    if grep -q '^GITEA_ENABLED=' .env 2>/dev/null; then
      sed_inplace 's|^GITEA_ENABLED=.*|GITEA_ENABLED=false|' .env
    fi
    info "GITEA_ENABLED=false"

    cat <<EOF

=== Back on github.com

  git push                        # get the reverted gitops/ URLs onto github
  make cp-apply ph-apply app-apply argo-apply
EOF
    ;;

  *)
    cat >&2 <<EOF
usage: $(basename "$0") gitea|github

  gitea   point Octopus CaC, Platform Hub, and Argo CD at the local Gitea
  github  revert everything to github.com

Current state: GITEA_ENABLED=$(grep '^GITEA_ENABLED=' .env 2>/dev/null | cut -d= -f2 || echo "unset")
EOF
    exit 2
    ;;
esac
