#!/usr/bin/env bash
#
# Flip the lab between github.com and the local Gitea instance.
#
#   ./compose/set-git-backend.sh gitea    # offline / conference mode
#   ./compose/set-git-backend.sh github   # back to normal
#
# Two mechanisms, because the git URL lives in two kinds of place:
#
#   1. OpenTofu stacks — handled by generating `gitea.auto.tfvars` per stack.
#      Note this can't be done with TF_VAR_* env vars: `cac_repo_url` and
#      `ph_repo_url` are set in each stack's committed `defaults.auto.tfvars`,
#      and *.auto.tfvars files OUTRANK environment variables in OpenTofu's
#      precedence order, so a TF_VAR_ export would be silently ignored.
#      *.auto.tfvars load lexicographically with later files winning, and
#      "gitea" sorts after "defaults", so this override lands on top.
#      Switching back = deleting the file.
#
#   2. gitops/ YAML and .octopus/ OCL — these are read from git by Argo CD and
#      Octopus, not rendered by tofu, so they need real text edits committed
#      to the branch. That's what the sed pass below does.
#
# Credentials are NOT touched here. The Makefile swaps them at apply time
# based on GITEA_ENABLED in .env, so no secret ends up in a tfvars file.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

BACKEND="${1:-}"
GITEA_USER="${GITEA_ADMIN_USER:-admin}"
GITEA_REPO="${GITEA_REPO:-octopus-iac-lab}"

# github.com forms
GH_WEB="https://github.com/creid-octopus/octopus-iac-lab"
GH_GIT="https://github.com/creid-octopus/octopus-iac-lab.git"
GH_CLONE="https://x-access-token:#{GitHub.Token}@github.com/creid-octopus/octopus-iac-lab.git"

# Gitea forms. host.docker.internal, NOT localhost or `gitea` — it's the only
# address that resolves from BOTH the Octopus container and Kubernetes pods.
# Verified: resolves to 192.168.65.254 in-cluster. See docs/local-gitea.md.
GT_WEB="http://host.docker.internal:3000/${GITEA_USER}/${GITEA_REPO}"
GT_GIT="http://host.docker.internal:3000/${GITEA_USER}/${GITEA_REPO}.git"
GT_CLONE="http://${GITEA_USER}:#{GitHub.Token}@host.docker.internal:3000/${GITEA_USER}/${GITEA_REPO}.git"

TFVARS_STACKS=(tofu/control-plane tofu/app-randomquotes tofu/platform-hub tofu/argocd)

step() { printf '\n=== %s\n' "$*"; }
info() { printf '    %s\n' "$*"; }

# In-place sed differs between BSD (macOS, needs an explicit empty suffix)
# and GNU (Linux, rejects it). Detect once rather than assuming macOS, so
# this is testable in a Linux container too.
if sed --version >/dev/null 2>&1; then
  sed_inplace() { sed -i "$@"; }
else
  sed_inplace() { sed -i '' "$@"; }
fi

# Rewrite one URL form to another across the files that hold it.
#
# Order within the sed matters: the credential-bearing clone URL and the
# `.git` form both CONTAIN the bare web form as a prefix, so they have to be
# replaced first or the bare-form rule would mangle them into a hybrid.
# `|` is the sed delimiter since every URL here contains `/` but none
# contain `|`. grep -F keeps the `.` in hostnames from acting as a wildcard.
flip_files() {
  local from_clone="$1" to_clone="$2" from_git="$3" to_git="$4" from_web="$5" to_web="$6"
  local changed=0 f

  while IFS= read -r f; do
    sed_inplace \
      -e "s|${from_clone}|${to_clone}|g" \
      -e "s|${from_git}|${to_git}|g" \
      -e "s|${from_web}|${to_web}|g" \
      "$f"
    info "  $f"
    changed=$((changed + 1))
  done < <(grep -rlF -e "${from_web}" -e "${from_clone}" \
             --include="*.yaml" --include="*.yml" --include="*.ocl" \
             gitops .octopus 2>/dev/null | sort -u)

  info "rewrote ${changed} file(s)"
}

case "${BACKEND}" in
  gitea)
    step "Switching tofu stacks to Gitea"
    for s in "${TFVARS_STACKS[@]}"; do
      case "$s" in
        tofu/control-plane|tofu/app-randomquotes)
          cat > "${s}/gitea.auto.tfvars" <<EOF
# Generated by compose/set-git-backend.sh — do not commit, do not hand-edit.
# Overrides defaults.auto.tfvars (loads later alphabetically). Remove this
# file, or run \`make gitea-disable\`, to go back to github.com.
cac_repo_url = "${GT_GIT}"
EOF
          ;;
        tofu/platform-hub)
          cat > "${s}/gitea.auto.tfvars" <<EOF
# Generated by compose/set-git-backend.sh — do not commit, do not hand-edit.
ph_repo_url = "${GT_WEB}"
EOF
          ;;
        tofu/argocd)
          cat > "${s}/gitea.auto.tfvars" <<EOF
# Generated by compose/set-git-backend.sh — do not commit, do not hand-edit.
gitops_repo_url = "${GT_WEB}"
EOF
          ;;
      esac
      info "wrote ${s}/gitea.auto.tfvars"
    done

    step "Rewriting gitops/ + .octopus/ URLs to Gitea"
    flip_files "${GH_CLONE}" "${GT_CLONE}" "${GH_GIT}" "${GT_GIT}" "${GH_WEB}" "${GT_WEB}"

    step "Recording the switch in .env"
    if grep -q '^GITEA_ENABLED=' .env 2>/dev/null; then
      sed_inplace 's|^GITEA_ENABLED=.*|GITEA_ENABLED=true|' .env
    else
      echo "GITEA_ENABLED=true" >> .env
    fi
    info "GITEA_ENABLED=true — the Makefile now points Octopus's git credential at Gitea"

    cat <<EOF

=== Now on Gitea

Apply order matters. The gitops/ edits above only take effect once they're
IN Gitea, so push before applying Argo:

  make gitea-push                 # get the rewritten gitops/ URLs into Gitea
  make cp-apply ph-apply app-apply   # Octopus CaC + Platform Hub → Gitea
  make argo-apply                 # bootstrap Application → Gitea

Then verify per docs/local-gitea.md ("After switching backends").
EOF
    ;;

  github)
    step "Removing Gitea tofu overrides"
    for s in "${TFVARS_STACKS[@]}"; do
      if [ -f "${s}/gitea.auto.tfvars" ]; then
        rm "${s}/gitea.auto.tfvars"
        info "removed ${s}/gitea.auto.tfvars"
      fi
    done

    step "Rewriting gitops/ + .octopus/ URLs back to github.com"
    flip_files "${GT_CLONE}" "${GH_CLONE}" "${GT_GIT}" "${GH_GIT}" "${GT_WEB}" "${GH_WEB}"

    step "Recording the switch in .env"
    if grep -q '^GITEA_ENABLED=' .env 2>/dev/null; then
      sed_inplace 's|^GITEA_ENABLED=.*|GITEA_ENABLED=false|' .env
    fi
    info "GITEA_ENABLED=false"

    cat <<EOF

=== Back on github.com

  git push                        # get the reverted gitops/ URLs onto github
  make cp-apply ph-apply app-apply argo-apply
EOF
    ;;

  *)
    cat >&2 <<EOF
usage: $(basename "$0") gitea|github

  gitea   point Octopus CaC, Platform Hub, and Argo CD at the local Gitea
  github  revert everything to github.com

Current state: GITEA_ENABLED=$(grep '^GITEA_ENABLED=' .env 2>/dev/null | cut -d= -f2 || echo "unset")
EOF
    exit 2
    ;;
esac
